apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "task-system.webImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 80
